name: Send Email with EmailJS on Push

on:
  push:
    branches:
      - main

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: Send email using EmailJS
        run: |
          curl -X POST https://api.emailjs.com/api/v1.0/email/send \
            -H "origin: https://github.com" \
            -H "Content-Type: application/json" \
            -d '{
              "service_id": "${service_jgap5ij}",
              "template_id": "${emplate_luej17l}",
              "user_id": "${vqYyv2J3u7inIVDaR}",
              "template_params": {
                  "subject": "New Push to GitHub Repo!",
                  "message": "I pushed to the github 🚀"
              }
            }'
